theislab/scib

R/visualization/plotBestMethodsATAC.R
R/visualization/plotBestMethodsAcrossAtlases.R

by assigning unintegrated scores to methods that do not run on a certain atlas.

changed ranking

---

scIB/integration.py

The saucie function didn't work with dense input, this fixes that

Error for saucie if input is dense

---

scIB/preprocessing.py

[This](https://github.com/theislab/scib/commit/3a483caa79e0dcc67b738548ab350f72b45ecd50) commit broke the plotQC function as palette is not defined anymore. This should fix that

Removed undefined palette definition

---

scIB/metrics.py

added isolated label fix (argmax indexing)

Fixing F1 isolated label score

---

scIB/preprocessing.py

Revert "Enable Bioconductor 3.11 compatibility"

---

scIB/metrics.py

Only use the largest connected component for dpt calculation in post integration object.
Tested in a jupyter notebook so far.

changed trajectory metric to only consider largest connected component

---

scIB/metrics.py

Catch metrics errors arising for low quality input.
Not tested yet

Catch metrics errors

---

R/integration.R
config.yaml
scripts/runMethods.R

Add Seurat alignment mode using RPCA to find anchors.

added Seurat RPCA mode

---

scIB/preprocessing.py

This PR addresses #192. Scran pooling normalization now checks for 0 count cell or gene input.

Added error checks for scran normalization

---

scIB/metrics.py

fix bug in silhouete calculation

---

requirements.txt

update anndata and scanpy #242

update scanpy and anndata

---

scIB/metrics.py

Remove redundant cc score code

---

.github/workflows/python-package.yml
scIB/metrics/cell_cycle.py
scIB/metrics/graph_connectivity.py
scIB/metrics/isolated_labels.py
scIB/metrics/lisi.py
scIB/metrics/metrics.py
scIB/metrics/nmi.py
scIB/metrics/pcr.py
scIB/metrics/silhouette.py
tests/metrics/test_all.py
tests/metrics/test_beyond_label_metrics.py
tests/metrics/test_graph_connectivity.py
tests/metrics/test_silhouette_metrics.py
tests/metrics/test_trajectory.py

Making sure all metrics are doing what we expect them to.

Check metrics

---

scIB/metrics/trajectory.py
tests/metrics/test_trajectory.py

Add functionality to compute trajectory score per batch and take the mean and not compute the score overall.

add per batch trajectory score

---

scib/metrics/metrics.py

Added embed to opt_louvain in metrics function (#277)

---

scib/metrics/lisi.py
tests/metrics/test_clisi.py

Fixed cLISI scaling to be dependent on n_labels rather than n_batches.
Todo:

[WIP] fixed clisi scaling bug

---

scib/metrics/metrics.py

`clisi_` should not be a `tuple`, but a `bool` value.

Remove `,` in `bool` var

---

scib/exceptions.py
scib/metrics/kbet.py
scib/metrics/lisi.py
scib/preprocessing.py
setup.cfg

Addressing issues listed under https://github.com/theislab/scib-pipeline/issues/23
> Things to improve installation experience:
> * [x] pin rpy2 3.4.2
>   * install specifically via conda (if possible)
> * [x] scib: try-except around ro.r('library(Seurat)’) to report that library installs were problematic

Addressing installation issues

---

.github/workflows/test.yml
.gitignore
scib/utils.py
tests/integration/test_scanorama.py
tests/preprocessing/test_clustering.py
tests/preprocessing/test_preprocessing.py

Fix scanorama batch reordering

---

scIB/preprocessing.py

Louvain is buggy and not recommended, as per https://github.com/theislab/scanpy/issues/1191#issuecomment-622229246

Add option to use leiden

---

scib/integration.py
setup.cfg

This also correctly pipes the hvg argument to be used for scvi-tools models. Not sure what is correct here.

Update to scvi tools again, also scgen which now uses scvi tools

---

.github/workflows/test.yml
scib/integration.py
tests/integration/test_scanvi.py
tests/integration/test_scvi.py

Addresses #324 and https://github.com/theislab/scib-pipeline/issues/41

Fix scanvi bug

---

scib/metrics/silhouette.py
tests/metrics/test_silhouette_metrics.py

Fix batch silhouette bug

---

scib/metrics/__init__.py
scib/metrics/clustering.py
tests/preprocessing/test_clustering.py

Create a new function for clustering for optimal resolution. Allows the user to specify whether they want to use the louvain, leiden or any other algorithm that works with an anndata and a cluster resolution.
Closes #340

General optimised clustering function

---

docs/source/api.rst

Fix sc best practices link

---

tests/metrics/test_isolated_label.py

Add perfect isolabel ASW test

---

scib/metrics/isolated_labels.py
tests/metrics/test_isolated_label.py
tests/metrics/test_silhouette_metrics.py

Iso label ASW as discussed on friday. Tested locally in jupyter notebook returning 1 for baseline dataset.

Run iso label as discussed on friday
