theislab/scib

setup.py

```
File "/home/travis/build/singlecellopenproblems/SingleCellOpenProblems/openproblems/tools/normalize.py", line 14, in log_scran_pooling
scIB.preprocessing.normalize(adata)
File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/scIB/preprocessing.py", line 166, in normalize
sc.tl.louvain(adata_pp, key_added='groups', resolution=0.5)
File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/scanpy/tools/_louvain.py", line 131, in louvain
g = _utils.get_igraph_from_adjacency(adjacency, directed=directed)
File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/scanpy/_utils.py", line 192, in get_igraph_from_adjacency
import igraph as ig
ModuleNotFoundError: No module named 'igraph'
```

Add igraph to dependencies

---

setup.py

Same issue as igraph, this is an optional dependency in scanpy.

Add louvain dependency

---

Snakefile
config.yaml
scIB/metrics.py
scIB/preprocessing.py
scripts/metrics.py
scripts/runPP.py
scripts/snakemake_parse.py

Fixed snakemake structure to allow for running metrics on unintegrated data.
- The unintegrated adata was preprocessed with `runPP.py` prior to metric computation. This was not the case before.
- unintegrated metrics are done for each scaling, feature subset and scenario
- unintegrated metrics files separated from integrated metrics files  `{scenario}/metrics_unintegrated/`
- unintegrated metrics are added to the final `metrics.csv` file

Unintegrated metrics

---

scIB/preprocessing.py

Scran normalization wasn't compatible with Bioconductor 3.11 as implemented. `computeSumFactors()` now exclusively takes `SingleCellExperiment` objects as input.
This fixes #141

Enable Bioconductor 3.11 compatibility

---

R/integration.R

For Harmony and fastMNN now store embeddings using `sobj[['X_emb']]` instead of `sobj@reductions['X_emb']`
Fixes #166 (hopefully)

Modify how embeddings are stored in Seurat objects

---

scIB/preprocessing.py

This PR relates to issue #155 
Running `scIB.pp.normalize()` starts an `R` kernel which requires memory that is not freed after running the function. 
Several things to try:

[WIP] Free memory after running normalize

---

scIB/integration.py

The n_epochs_scANVI somehow returns a float sometimes, this fixes that behaviour.

Fix small bug in scanvi function

---

scIB/clustering.py

**Problem**: Clustering does not use optimised resolution but last resolution of search space.
**Solution**: Corrected typo that broke finding optimal score for clustering.
This affects all metrics and other operations reliant on optimised clustering. If we have conclusions based on the clustering-based metrics, we might want to re-evaluate the metrics with this bugfix, if it is still feasible.

Fix finding optimal resolution for clustering

---

Snakefile
scripts/merge_benchmarks.py
scripts/snakemake_parse.py

This PR adds a script and Snakemake rule for merging all the `.benchmark` files produced by the main pipeline (when timing is turned on). It is not part of the main pipeline and needs to be run separately after that is complete. The output is a `benchmarks.csv` file in the same location as the `metrics.csv` file.
Briefly what the script does is:
1. Search the root output directory for files in an `integration/` direction ending in `.benchmark`
2. Read in these files and concatenate them
3. Save the result
The output file can then be easily used to compare the scalability of methods.

Merge benchmarks into a single output file

---

scIB/metrics.py
scripts/metrics.py

Recomputed isolated label due to ineffective cluster optimisation.
The isolated label score now optimises cluster resolution by F1 score between cluster assignment and isolated cell label. This is done for each isolated cell label separately.

Isolated label fix

---

scripts/save_embeddings.py

This was a bit trickier than I thought because I think the pipeline will complain if there is no output. What I have done is:
1. Check if the input `.h5ad` file is empty, if yes:
1. Delete any existing embedding output files
1. Create empty output files
I think it works but I have only tested it very quickly so probably good if @danielStrobl can try running it before we merge.

Handle empty input files when saving embedding plots

---

scIB/metrics.py

I replace some values in the connectivities matrix by the minimum value allowed as double in C++ (i.e. `1.7e-308`). Code is tested on two examples, however, I was unable to reproduce Luke's error message, when I set some values in the connectivities matrix to values smaller than `1.7e-308`.

Fix LISI error for small values

---

scIB/preprocessing.py

Best practice is probably to use local converters instead. 
https://github.com/theislab/anndata2ri/issues/50

Deactivate anndata2ri after preprocessing

---

scIB/integration.py
scIB/metrics.py
scIB/utils.py

When we use `Anndata.concatenate` and specify the `batch_key` parameter, we need to ensure that the correct batch categories are passed to the method as well. Otherwise these will be overwritten with batches `0:n_batches-1`.
On the test data, the batch key is 'batch', the same as the default value of `batch_key` in `Anndata.concatenate`. This results in shuffled batches after concatenating anndata objects split by batch.
Fixes
- provide option in `utils.splitBatches` to return the batches categories
- pass batch categories to `Anndata.concatenate` function together with `batch_key`, so that correct batch annotations are retained

Fix: Anndata concatenate causes shuffled batches

---

scIB/metrics.py

Currently metric assumes pseudotime to be saved under 'dpt_pseudotime'. For some use-cases we would want to be able to specifiy different pseudotime columns in `.obs`.

Allow specific pseudotime column for TI metric

---

scIB/metrics.py

Some bugs found when `pseudotime_key` is not 'dpt_pseudotime'

Fix TI metric

---

scIB/preprocessing.py

If cells are filtered in this stage, scran throws an error: 
`error in evaluating the argument 'object' in selecting a method for function 'sizeFactors': 'ncol(x)' is not equal to 'length(clusters)'`

Avoid filtering in normalization

---

.github/workflows/test.yml
setup.cfg

Unpin rpy2 dependency and make sure test run through without failing. This will close #322 
Skipping pytest on macos (due to unresolved segmentation fault)

Bump rp2y dependency

---

scib/integration.py

Passing `max_epochs=None` to `SCVI.train` throws an error.
```pytb
File "/usr/local/lib/python3.8/site-packages/scib/integration.py", line 280, in scanvi
vae = scvi(adata, batch, hvg, return_model=True, max_epochs=n_epochs_scVI)
File "/usr/local/lib/python3.8/site-packages/scib/integration.py", line 242, in scvi
vae.train(train_size=1.0, max_epochs=max_epochs)
File "/usr/local/lib/python3.8/site-packages/scvi/model/base/_training_mixin.py", line 142, in train
return runner()
File "/usr/local/lib/python3.8/site-packages/scvi/train/_trainrunner.py", line 82, in __call__
self.trainer.fit(self.training_plan, self.data_splitter)
File "/usr/local/lib/python3.8/site-packages/scvi/train/_trainer.py", line 188, in fit
super().fit(*args, **kwargs)
File …
```

Only pass max_epochs to SCVI.train if set

---

.github/workflows/test.yml
README.md
scib/exceptions.py
scib/metrics/kbet.py
tests/metrics/rpy2/test_kbet.py

Fix kBET import issue

---

setup.cfg

A new version of louvain has been released after quite some time. This PR updates scIB to use the new version, unpinning igraph.

Update louvain to 0.8

---

.github/workflows/test.yml
scib/metrics/clustering.py
setup.cfg
tests/conftest.py
tests/integration/test_harmony.py
tests/integration/test_scanorama.py
tests/metrics/test_cluster_metrics.py

Make louvain an optional dependency

---

scib/metrics/isolated_labels.py
tests/metrics/test_isolated_label.py
tests/metrics/test_silhouette_metrics.py

Isolated label ASW is not scaled, so that the expected output range would be between -1 and +1
https://github.com/theislab/scib/blob/98ee9a20260993ca5df960054dcc82ff8fd75b20/scib/metrics/isolated_labels.py#L237-L249
**Solution:** Add scaling option to metric

Scale isolated label ASW

---

.github/workflows/test.yml
scib/_package_tools.py
scib/metrics/ari.py
scib/metrics/highly_variable_genes.py
scib/metrics/nmi.py
scib/metrics/pcr.py
scib/metrics/silhouette.py
scib/utils.py
tests/common.py
tests/conftest.py
tests/integration/test_scanvi.py
tests/integration/test_scvi.py
tests/metrics/test_beyond_label_metrics.py

After scanpy 1.9.6, the `deprecated_arg_names` function was replaced with `renamed_args`.
This PR uses the `renamed_args` instead (and is backwards compatible).
Closes #401 
Closes #403

Fix argument deprecation

---

docs/source/api.rst
scib/metrics/clustering.py
scib/metrics/isolated_labels.py
setup.cfg
tests/integration/test_harmony.py
tests/integration/test_scanorama.py
tests/integration/test_scanvi.py
tests/integration/test_scvi.py
tests/metrics/test_isolated_label.py
tests/preprocessing/test_clustering.py

Improve performance of clustering function to reduce redundant kNN and clustering operations
* `cluster_optimal_resolution` will not rerun `sc.pp.neighbors` or clustering by default if cluster key exists for the specified resolution (by name matching)`
* update `get_resolutions` function to scale equally between 0 and n

Use precomputed clustering

---

setup.cfg

Please see https://github.com/igraph/python-igraph/issues/699 for an explanation. This is one of the most popular packages on PyPI that still depends on the deprecated `python-igraph` package name.

Update python-igraph dependency to igraph

---

scib/metrics/utils.py

In some versions of scipy(e.g. 1.14), M.A might not be available. In such cases, you should use M.toarray() to convert the sparse matrix to a dense one.

M.A might not be available, you should use M.toarray()
